# Generated by Django 2.2.12 on 2020-07-08 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_sing_singer'),
        ('shopping', '0002_auto_20200708_0850'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='sing',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
        ),
        migrations.AddField(
            model_name='sing',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Singer'),
        ),
    ]
