# Generated by Django 2.2.12 on 2020-07-08 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_sing_singer'),
        ('user', '0001_initial'),
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_time', models.DateTimeField(verbose_name='购买时间')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
                ('sing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Sing')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Singer')),
            ],
        ),
        migrations.DeleteModel(
            name='ShoppingHistory',
        ),
    ]
